# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='forgotten_notify_date',
            field=models.DateTimeField(null=True, verbose_name='Date when notification sent about forgotten'),
        ),
    ]
